version: '3.8'

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      - app-network
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    profiles: [ "dev", "prod" ]

  backend:
    build:
      context: ./backend
      target: prod
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
      - SESSION_AUTH_KEY=${SESSION_AUTH_KEY}
      - SESSION_ENC_KEY=${SESSION_ENC_KEY}
    restart: unless-stopped
    networks:
      - app-network
    profiles: [ "prod" ]

networks:
  app-network:
    driver: bridge